### ISSUE TITLE
Random OperationCanceledException 

### ISSUE THREAD

**Issue by Talento90** [aws/aws-aspnet-cognito-identity-provider#115]
Hello, I am using `AmazonCognitoIdentityProviderClient` to create users using the the following method `AdminCreateUserAsync` and then `AdminSetUserPasswordAsync`. Most of the times it works perfectly but some times it throws `System.OperationCanceledException`. It seems that the Http Client is timing out randomly... 

Framework: .NET 4.5.x

```
System.OperationCanceledException: The request was aborted: The request was canceled. ---> System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
```

**Comment by klaytaybai** [comment]
This sounds like it might be tricky to reproduce and investigate.  Are you able to provide us with any more information that might help?   How is your network connection?  What environment are you running in?  How are you using credentials?  What is your timeout set to?

**Comment by Talento90** [comment]
Yes, it's quite tricky. We are running our application as App Service in Azure (North Europe). We are using the default Timeout, I have not change any configuration.

**Comment by assyadh** [comment]
Hi @Talento90 ,

How are you creating your UserPool client and AmazonCognitoIdentityProviderClient object?

How do you handle the credentials?

H.

**Comment by Talento90** [comment]
UserPool is created manually using the AWS Cognito UI. 

Basically we just create a `BasicAWSCredentials` using key and secret.
```
var region = RegionEndpoint.GetBySystemName("region");
var credentials = new BasicAWSCredentials(key, secret);
var client = new AmazonCognitoIdentityProviderClient(credentials, region);
```

**Comment by Talento90** [comment]
@assyadh At this moment my wrapper around Cognito is a Singleton should I change for a lifetime request? Cognito client has some kind of lifetime?

**Comment by ashishdhingra** [comment]
Hi @Talento90,

I don't think the Singleton wrapper around Cognito should be an issue. However, if using temporary credentials, you would need to handle scenario where credentials expire and refresh is needed. I'm not sure if this is your scenario and if it could be causing the issue. 

Please let me know if this issue could be closed if this is no longer an issue.

Thanks,
Ashish
