### ISSUE TITLE
 System.TypeLoadException: Method 'NormalizeName' after upgrading to 1.0.4

### ISSUE THREAD

**Issue by MarneeDear** [aws/aws-aspnet-cognito-identity-provider#142]
I have a project where I was running 1.0.2. And it was working fine, but after upgrading to 1.0.4 I get this error:

```
Unhandled Exception: System.TypeLoadException: Method 'NormalizeName' in type 'Amazon.AspNetCore.Identity.Cognito.CognitoKeyNormalizer' from assembly 'Amazon.AspNetCore.Identity.Cognito, Version=1.0.4.0, Culture=neutral, PublicKeyToken=885c28607f98e604' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.CognitoServiceCollectionExtensions.InjectCognitoUser[TUser](IServiceCollection services, Action`1 identityOptions)
   at Microsoft.Extensions.DependencyInjection.CognitoServiceCollectionExtensions.AddCognitoIdentity(IServiceCollection services, Action`1 identityOptions, String prefix)
   at Server.configureServices(IServiceCollection services) in C:\Users\marnee\Documents\mister\application\mister-portal-cognitoupdate\src\Mister.WebHost\Program.fs:line 98
   at Server.app@167-3.Invoke(IServiceCollection services) in C:\Users\marnee\Documents\mister\application\mister-portal-cognitoupdate\src\Mister.WebHost\Program.fs:line 167
   at Saturn.Application.Run@77-2.Invoke(FSharpFunc`2 fn) in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Application.fs:line 77
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Saturn.Application.Run@75-1.Invoke(IServiceCollection svcs) in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Application.fs:line 77
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Saturn.Application.run(IWebHostBuilder app) in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Application.fs:line 570
   at Server.main(String[] _arg1) in C:\Users\marnee\Documents\mister\application\mister-portal-cognitoupdate\src\Mister.WebHost\Program.fs:line 177
```

I am running on .Net core runtime version `2.2.105`

Is the latest version not compatible with this .Net core version? There was a fix to the way it handled password requirements, and I need this in my project, but I am not ready to upgrade to 3.0. Any suggestions?

**Comment by klaytaybai** [comment]
Hi @MarneeDear.  I'm not sure why you would be seeing this error.  .NET Core 2.2 should be using the Normalize method, not NormalizeName.  There might be something wrong with your csproj file.  Could you please provide a small sample app that reproduces the problem?

**Comment by MarneeDear** [comment]
Yes, I will work on that. Thank you.

**Comment by klaytaybai** [comment]
I'm closing this for now.  Feel free to reopen it if you can provide a reproduction solution.
