### ISSUE TITLE
Getting error "Unable to get IAM security credentials from EC2 Instance Metadata Service." while trying to login

### ISSUE THREAD

**Issue by Ace-Lightning** [aws/aws-aspnet-cognito-identity-provider#202]
## The Question
I'm trying to implement Cognito into my .NET Core Web API but I'm getting follow error while trying to execute command `var result = await signInManager.CheckPasswordSignInAsync(user, loginQuery.Password, false);`

```log
Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.AspNetCore.Identity.Cognito.CognitoUserStore`1.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken)
   at Amazon.AspNetCore.Identity.Cognito.CognitoUserManager`1.FindByEmailAsync(String email)
   at AuthenticationAPI.Controllers.LoginController.Login(LoginQuery loginQuery) in C:\Users\SergeyKoryshev\source\repos\AuthenticationAPI\server\AuthenticationAPI\Controllers\LoginController.cs:line 30
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Code of `LoginController`:

```csharp
using Amazon.Extensions.CognitoAuthentication;
using AuthenticationAPI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AuthenticationAPI.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class LoginController : ControllerBase
    {
        private readonly SignInManager<CognitoUser> signInManager;
        private readonly UserManager<CognitoUser> userManager;

        public LoginController(SignInManager<CognitoUser> signInManager, UserManager<CognitoUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> Login([FromBody] LoginQuery loginQuery)
        {
            CognitoUser user = await userManager.FindByEmailAsync(loginQuery.Email);

            if (user == null)
            {
                return Unauthorized();
            }

            var result = await signInManager.CheckPasswordSignInAsync(user, loginQuery.Password, false);

            if (result.Succeeded)
            {
                return Ok(new User
                {
                    Token = "test",
                    Email = loginQuery.Email
                });
            }

            return Unauthorized();
        }
    }
}
```

I have followed steps you provided in Readme.md of the repository. Could you please help me to figure out what have I missed?

### Environment
* Build Version: Amazon.AspNetCore.Identity.Cognito (3.0.0); Amazon.Extensions.CognitoAuthentication (2.2.2)
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET 5.0

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @Ace-Lightning,

Good morning.
 
Thanks for posting guidance question. Could you please share how your credentials are configured? Kindly refer [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html) for the guidance on how credentials are resolved.

Thanks,
Ashish

**Comment by Ace-Lightning** [comment]
Hi @ashishdhingra 

I store credentials in environment variables
![image](https://user-images.githubusercontent.com/11807074/129312066-a032d6bd-98ec-426f-8a73-b28849f69b25.png)

**Comment by Ace-Lightning** [comment]
Okay I figured it out, I run it in docker contains and I needed to pass environment variables into it. Once I did it my application work as expected.

Sorry to disturb you.
